/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterSellerRouteImport } from './routes/register.seller'
import { Route as RegisterCustomerRouteImport } from './routes/register.customer'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSellerRoute = RegisterSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterCustomerRoute = RegisterCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => RegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/register/customer': typeof RegisterCustomerRoute
  '/register/seller': typeof RegisterSellerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/register/customer': typeof RegisterCustomerRoute
  '/register/seller': typeof RegisterSellerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/register/customer': typeof RegisterCustomerRoute
  '/register/seller': typeof RegisterSellerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/register/customer'
    | '/register/seller'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/register/customer' | '/register/seller'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/register/customer'
    | '/register/seller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/seller': {
      id: '/register/seller'
      path: '/seller'
      fullPath: '/register/seller'
      preLoaderRoute: typeof RegisterSellerRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/customer': {
      id: '/register/customer'
      path: '/customer'
      fullPath: '/register/customer'
      preLoaderRoute: typeof RegisterCustomerRouteImport
      parentRoute: typeof RegisterRoute
    }
  }
}

interface RegisterRouteChildren {
  RegisterCustomerRoute: typeof RegisterCustomerRoute
  RegisterSellerRoute: typeof RegisterSellerRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterCustomerRoute: RegisterCustomerRoute,
  RegisterSellerRoute: RegisterSellerRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
